#!/usr/bin/env node
/**
 * patch_arch.js — rewrites index.html to:
 *   1. Remove all embedded data constants → load from data/*.js
 *   2. Remove parseCSV() — data is pre-parsed JSON
 *   3. Update init() to use window.BOARD_DATA etc.
 *   4. Add loading spinner
 *   5. Add pagination (50 rows/page)
 *   6. Add column toggle ⚙️ with localStorage persistence
 */
const fs = require('fs');
let html = fs.readFileSync('/home/user/Fantasy-Tracker/index.html', 'utf8');

// ─────────────────────────────────────────────────────────────────────────────
// 1. Add data script tags to <head> (before Google Fonts link)
// ─────────────────────────────────────────────────────────────────────────────
html = html.replace(
  `<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600;700&display=swap" rel="stylesheet">`,
  `<link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600;700&display=swap" rel="stylesheet">
<!-- Data files — pre-parsed JSON generated by build_data.js -->
<script src="data/players.js"></script>
<script src="data/idp.js"></script>
<script src="data/vorp.js"></script>
<script src="data/vegas.js"></script>
<script src="data/rounds.js"></script>`
);

// ─────────────────────────────────────────────────────────────────────────────
// 2. Remove all embedded data constants
//    These are from "const _RAW_BOARD = `" to just after `;\n\nconst _RAW_ROUNDS`
//    end marker is the next `;\n\n` after the rounds content
// ─────────────────────────────────────────────────────────────────────────────
const dataStart = html.indexOf('\nconst _RAW_BOARD = `');
const dataEndMarker = 'window.ROUNDS_MD';
// Find the end of the embedded data block: look for next const/function after the data
// The data block ends with: `;\n\n` followed by variable declarations
// Find: const _RAW_ROUNDS = `...`;\n\n
const roundsEnd = html.indexOf('`;\n\nconst _vegasMap', dataStart);
const roundsEnd2 = html.indexOf('`;\n\nwindow._vegasMap', dataStart);
const roundsEnd3 = html.indexOf('`;\n\nfunction ', dataStart);
const roundsEnd4 = html.indexOf('`;\n\nlet ', dataStart);

let dataEndIdx = -1;
[roundsEnd, roundsEnd2, roundsEnd3, roundsEnd4].forEach(i => {
  if (i > 0 && (dataEndIdx === -1 || i < dataEndIdx)) dataEndIdx = i;
});

if (dataStart === -1 || dataEndIdx === -1) {
  console.error('Could not find data block. dataStart:', dataStart, 'dataEnd:', dataEndIdx);
  // Try alternative
  const alt = html.indexOf('const _RAW_BOARD');
  console.log('Alt search:', alt);
  process.exit(1);
}

// Remove the data block (keep the newline before the next section)
const dataBlock = html.slice(dataStart, dataEndIdx + 2); // +2 for the `;\n
console.log('Data block starts with:', dataBlock.slice(0, 60));
console.log('Data block ends with:', dataBlock.slice(-60));
html = html.slice(0, dataStart) + '\n' + html.slice(dataEndIdx + 2);
console.log('✅ Removed embedded data constants');

// ─────────────────────────────────────────────────────────────────────────────
// 3. Remove parseCSV function (it's replaced by pre-parsed JSON)
// ─────────────────────────────────────────────────────────────────────────────
const parseFnStart = html.indexOf('\nfunction parseCSV(text){');
const parseFnEnd = html.indexOf('\nfunction init(){');
if (parseFnStart > 0 && parseFnEnd > parseFnStart) {
  html = html.slice(0, parseFnStart) + '\n' + html.slice(parseFnEnd);
  console.log('✅ Removed parseCSV function');
}

// ─────────────────────────────────────────────────────────────────────────────
// 4. Replace init() body to use window.BOARD_DATA instead of parseCSV
// ─────────────────────────────────────────────────────────────────────────────
const OLD_INIT = `function init(){
  board = parseCSV(_RAW_BOARD);
  idpData = parseCSV(_RAW_IDP);
  vegasData = parseCSV(_RAW_VEGAS);
  vorpData = parseCSV(_RAW_VORP);
  roundMD = _RAW_ROUNDS;

  board.forEach(p=>{
    p.my_rank=n(p.my_rank)||999; p.consensus_rank=n(p.consensus_rank)||999;
    p.age=n(p.age); p.value_gap=n(p.value_gap);
    p.gem_flag=n(p.gem_flag);
    p.dp_value_2qb=p.dp_value_2qb!==''?n(p.dp_value_2qb):null;
    p.dp_rank_2qb=p.dp_rank_2qb!==''?n(p.dp_rank_2qb):null;
    p.dp_vs_my_rank=p.dp_vs_my_rank!==''?n(p.dp_vs_my_rank):null;
    p.is_rookie=n(p.is_rookie)||0;
    p.future_value=n(p.future_value);
    p.target_round=n(p.target_round)||10; p.adp_round=n(p.adp_round)||10;
    p.vorp_adjusted=n(p.vorp_adjusted); p.vorp_2qb_adjusted=p.vorp_2qb_adjusted!==''?n(p.vorp_2qb_adjusted):null;
    p.proj_pts_2026=n(p.proj_pts_2026); p.ceiling_score=n(p.ceiling_score);
    p.floor_score_v2=n(p.floor_score_v2)||n(p.floor_score);
    p.future_value=n(p.future_value); p.master_score=n(p.master_score);
    p.injury_risk_score=n(p.injury_risk_score);
    p.games_missed_2025=n(p.games_missed_2025);
    p.games_missed_2024=n(p.games_missed_2024);
  });
  idpData.forEach(p=>{
    ['proj_fppg','proj_sacks','proj_solo_tackles','proj_ints','proj_tfl','age']
      .forEach(c=>p[c]=n(p[c]));
  });
  vegasData.forEach(p=>p.win_total=n(p.win_total));
  vorpData.forEach(p=>{
    ['vorp_rank','vorp_raw','vorp_adjusted','drop_to_next','drop_pct']
      .forEach(c=>p[c]=n(p[c]));
    p.vorp_2qb_adjusted=p.vorp_2qb_adjusted!==''?n(p.vorp_2qb_adjusted):null;
    p.te_premium_pts=n(p.te_premium_pts);
  });

  window._vegasMap={};
  vegasData.forEach(p=>{ window._vegasMap[p.player?.toLowerCase()]= p; });

  renderStatCards();
  renderBoard();
  initDraftState();
}`;

const NEW_INIT = `function init(){
  // Data loaded from data/*.js — already typed (numbers are numbers, not strings)
  board = window.BOARD_DATA || [];
  idpData = window.IDP_DATA || [];
  vegasData = window.VEGAS_DATA || [];
  vorpData = window.VORP_DATA || [];
  roundMD = window.ROUNDS_MD || '';

  if(!board.length){ throw new Error('BOARD_DATA not loaded — check data/players.js'); }

  // Ensure my_rank defaults (data is pre-typed but guard against nulls)
  board.forEach(p=>{
    if(!p.my_rank || p.my_rank < 1) p.my_rank = 999;
    if(!p.consensus_rank || p.consensus_rank < 1) p.consensus_rank = 999;
    if(!p.target_round) p.target_round = 10;
    if(!p.vorp_adjusted) p.vorp_adjusted = 0;
    if(!p.master_score) p.master_score = 50;
    if(!p.injury_risk_score) p.injury_risk_score = 3.0;
  });

  window._vegasMap={};
  vegasData.forEach(p=>{ window._vegasMap[p.player?.toLowerCase()]= p; });

  renderStatCards();
  renderBoard();
  initDraftState();
}`;

if (!html.includes(OLD_INIT)) {
  console.error('❌ OLD_INIT not found in file');
  // Debug: find what init looks like now
  const initIdx = html.indexOf('function init(){');
  if(initIdx >= 0) {
    console.log('Current init start:', html.slice(initIdx, initIdx+300));
  }
  process.exit(1);
}
html = html.replace(OLD_INIT, NEW_INIT);
console.log('✅ Updated init() to use window.BOARD_DATA');

// ─────────────────────────────────────────────────────────────────────────────
// 5. Remove the `n` helper (n=parseFloat) since we don't need to coerce strings
//    Actually keep it — it's still used in some places (scorecard bars etc)
// ─────────────────────────────────────────────────────────────────────────────
// Keep n() — used in scorecard bar rendering

// ─────────────────────────────────────────────────────────────────────────────
// 6. Add pagination state + column toggle state
// ─────────────────────────────────────────────────────────────────────────────
const OLD_BPOS_STATE = `let _bPos='ALL', _bSort={col:'master_score',dir:-1}, _bGem=false, _bSafe=false, _bCeil=false, _bBuyLow=false, _bRookie=false;`;
const NEW_BPOS_STATE = `let _bPos='ALL', _bSort={col:'master_score',dir:-1}, _bGem=false, _bSafe=false, _bCeil=false, _bBuyLow=false, _bRookie=false;
let _bPage=1; const PAGE_SIZE=50;
const ALL_COLS=[
  {k:'my_rank',   l:'Rank',     w:55},
  {k:'master_score',l:'⭐ Score',w:65},
  {k:'player',    l:'Player',   w:160},
  {k:'pos',       l:'Pos',      w:50},
  {k:'team',      l:'Team',     w:55},
  {k:'age',       l:'Age',      w:45},
  {k:'proj_pts_2026',l:'Proj',  w:55},
  {k:'vorp_adjusted',l:'VORP',  w:55},
  {k:'ceiling_score',l:'Ceil',  w:50},
  {k:'floor_score_v2',l:'Floor',w:50},
  {k:'injury_risk_score',l:'🩹',w:45},
  {k:'target_round',l:'Tgt',   w:45},
  {k:'dp_value_2qb',l:'DP Val', w:65},
  {k:'bust_category',l:'Flag',  w:110},
];
const DEFAULT_COLS=ALL_COLS.map(c=>c.k);
let _visibleCols;
function loadColPrefs(){ try{_visibleCols=JSON.parse(localStorage.getItem('dynasty_cols'))||[...DEFAULT_COLS];}catch{_visibleCols=[...DEFAULT_COLS];} }
function saveColPrefs(){ try{localStorage.setItem('dynasty_cols',JSON.stringify(_visibleCols));}catch{} }`;

if (!html.includes(OLD_BPOS_STATE)) {
  console.error('❌ BPOS_STATE not found'); process.exit(1);
}
html = html.replace(OLD_BPOS_STATE, NEW_BPOS_STATE);
console.log('✅ Added pagination + column toggle state');

// ─────────────────────────────────────────────────────────────────────────────
// 7. Update getFilteredBoard to reset page on filter change + pagination logic
// ─────────────────────────────────────────────────────────────────────────────
const OLD_GETFILTERED_END = `    return true;
  }).sort((a,b)=>{
    let av=a[_bSort.col],bv=b[_bSort.col];
    if(numCols.includes(_bSort.col)){av=+av||0;bv=+bv||0;}
    return av<bv?_bSort.dir:av>bv?-_bSort.dir:0;
  });
}`;

const NEW_GETFILTERED_END = `    return true;
  }).sort((a,b)=>{
    let av=a[_bSort.col],bv=b[_bSort.col];
    if(numCols.includes(_bSort.col)){av=+av||0;bv=+bv||0;}
    return av<bv?_bSort.dir:av>bv?-_bSort.dir:0;
  });
}
function getPagedBoard(all){ return all.slice((_bPage-1)*PAGE_SIZE, _bPage*PAGE_SIZE); }
function totalPages(all){ return Math.max(1,Math.ceil(all.length/PAGE_SIZE)); }`;

if (!html.includes(OLD_GETFILTERED_END)) {
  console.error('❌ getFilteredBoard end not found'); process.exit(1);
}
html = html.replace(OLD_GETFILTERED_END, NEW_GETFILTERED_END);
console.log('✅ Added getPagedBoard helper');

// ─────────────────────────────────────────────────────────────────────────────
// 8. Update setBPill + setBToggle to reset page
// ─────────────────────────────────────────────────────────────────────────────
html = html.replace(
  `function setBPill(pos, el){\n  _bPos=pos;`,
  `function setBPill(pos, el){\n  _bPos=pos; _bPage=1;`
);
html = html.replace(
  `  if(flag==='ROOKIE'){_bRookie=!_bRookie; el.classList.toggle('on',_bRookie);}`,
  `  if(flag==='ROOKIE'){_bRookie=!_bRookie; el.classList.toggle('on',_bRookie);}
  _bPage=1;`
);
html = html.replace(
  `  document.querySelectorAll('[id^="bs-"]').forEach(e=>e.textContent='');`,
  `  _bPage=1;
  document.querySelectorAll('[id^="bs-"]').forEach(e=>e.textContent='');`
);
html = html.replace(
  `  document.getElementById('boardQ')?.value||'').toLowerCase();`,
  `  _bPage=1;\n  (document.getElementById('boardQ')?.value||'').toLowerCase();`
);
console.log('✅ Page resets on filter/sort change');

// ─────────────────────────────────────────────────────────────────────────────
// 9. Replace renderBoard with paginated version + column-aware rendering
// ─────────────────────────────────────────────────────────────────────────────
const OLD_RENDER_BOARD = `const BUST_CAT_STYLE={`;
const OLD_RENDER_BOARD_END = `  document.getElementById('boardCount').textContent=\`Loaded: \${board.length} players | Showing: \${data.length}\`;
  console.log('[Board] loaded='+board.length+' showing='+data.length);
}`;

const renderBoardStart = html.indexOf(OLD_RENDER_BOARD);
const renderBoardEnd = html.indexOf(OLD_RENDER_BOARD_END);
if (renderBoardStart === -1 || renderBoardEnd === -1) {
  console.error('❌ renderBoard section not found', renderBoardStart, renderBoardEnd);
  process.exit(1);
}
const renderBoardEndFull = renderBoardEnd + OLD_RENDER_BOARD_END.length;

const NEW_RENDER_BOARD = `const BUST_CAT_STYLE={
  GEM:     {color:'var(--gem)',  icon:'💎', label:'GEM'},
  BUY_LOW: {color:'#f368e0',    icon:'📉', label:'BUY LOW'},
  RENTAL:  {color:'var(--idp)', icon:'⏱️', label:'RENTAL'},
  DECLINING:{color:'var(--bust)',icon:'📉', label:'DECLINING'},
  SCHEME_RISK:{color:'#ff9f43', icon:'🏟️', label:'SCHEME RISK'},
  SAFE:    {color:'var(--gem)', icon:'🟢', label:'SAFE'},
  NONE:    {color:'var(--muted)',icon:'',  label:'—'},
};
function bustBadge(p){
  const cat=p.bust_category||'NONE';
  const s=BUST_CAT_STYLE[cat]||BUST_CAT_STYLE.NONE;
  if(cat==='NONE') return '—';
  const tip=p.bust_reason?(' title="'+p.bust_reason.replace(/"/g,"'")+'"'):'';
  return \`<span\${tip} style="color:\${s.color};font-size:11px;cursor:help">\${s.icon} \${s.label}</span>\`;
}

function renderColToggle(){
  loadColPrefs();
  const wrap=document.getElementById('colTogglePanel');
  if(!wrap) return;
  wrap.innerHTML=ALL_COLS.map(c=>\`
    <label style="display:flex;align-items:center;gap:5px;padding:4px 0;cursor:pointer;font-size:12px">
      <input type="checkbox" onchange="toggleCol('\${c.k}',this.checked)" \${_visibleCols.includes(c.k)?'checked':''}>
      \${c.l}
    </label>
  \`).join('');
}
function toggleCol(key,on){
  if(on){ if(!_visibleCols.includes(key)) _visibleCols.push(key); }
  else { _visibleCols=_visibleCols.filter(k=>k!==key); }
  saveColPrefs();
  renderBoardHeader();
  renderBoard();
}
function renderBoardHeader(){
  const cols=ALL_COLS.filter(c=>_visibleCols.includes(c.k));
  document.getElementById('boardThead').innerHTML='<tr>'+cols.map(c=>
    \`<th onclick="setBSort('\${c.k}')" style="min-width:\${c.w}px">\${c.l}<span id="bs-\${c.k}">\${_bSort.col===c.k?(_bSort.dir===-1?' ▼':' ▲'):''}</span></th>\`
  ).join('')+'</tr>';
}

function renderBoard(){
  loadColPrefs();
  console.log('[renderBoard] board.length='+board.length+' page='+_bPage);
  const allData=getFilteredBoard();
  const tp=totalPages(allData);
  if(_bPage>tp) _bPage=tp;
  const data=getPagedBoard(allData);
  const cols=ALL_COLS.filter(c=>_visibleCols.includes(c.k));
  renderBoardHeader();
  document.getElementById('boardBody').innerHTML=data.map(p=>{
    const isBust=p.bust_category==='DECLINING'||p.bust_category==='RENTAL'||p.bust_category==='SCHEME_RISK';
    const rc=p.bust_category==='GEM'?'gem-r':isBust?'bust-r':'';
    const ms=p.master_score||0;
    const msC=ms>=85?'var(--qb)':ms>=75?'var(--gem)':ms>=65?'var(--boost)':ms>=55?'var(--idp)':'var(--muted)';
    const rC=riskColor(p.injury_risk_score||0);
    const cliff=p.cliff&&p.cliff!=='false'?\`<span style="color:\${p.cliff==='MAJOR'?'#ff3b3b':'#ff9f43'};font-size:10px"> \${p.cliff==='MAJOR'?'🚨':'⚠️'}</span>\`:'';
    const cells=cols.map(c=>{
      switch(c.k){
        case 'my_rank':         return \`<td><strong>\${p.my_rank||'—'}</strong></td>\`;
        case 'master_score':    return \`<td><strong style="color:\${msC}">\${ms||'—'}</strong></td>\`;
        case 'player':          return \`<td>\${p.bust_category==='GEM'?'💎 ':isBust?'⚠️ ':''}\${p.player}\${(p.injury_risk_score||0)>=7?' 🔴':''}\${cliff}\${p.is_rookie==1?' <span style="color:var(--qb);font-size:10px">🌟</span>':''}</td>\`;
        case 'pos':             return \`<td>\${posBadge(p.pos)}</td>\`;
        case 'team':            return \`<td>\${p.team}</td>\`;
        case 'age':             return \`<td>\${p.age||'—'}</td>\`;
        case 'proj_pts_2026':   return \`<td>\${p.proj_pts_2026||'—'}</td>\`;
        case 'vorp_adjusted':   return \`<td>\${p.vorp_adjusted>0?'+'+p.vorp_adjusted:'—'}</td>\`;
        case 'ceiling_score':   return \`<td>\${p.ceiling_score||'—'}</td>\`;
        case 'floor_score_v2':  return \`<td>\${p.floor_score_v2||'—'}</td>\`;
        case 'injury_risk_score':return \`<td style="color:\${rC};font-weight:700">\${p.injury_risk_score||'—'}</td>\`;
        case 'target_round':    return \`<td><span class="rnd-badge">R\${p.target_round||'?'}</span></td>\`;
        case 'dp_value_2qb':    return \`<td>\${p.dp_value_2qb?'<span style="color:var(--muted);font-size:11px">'+Number(p.dp_value_2qb).toLocaleString()+'</span>':'—'}</td>\`;
        case 'bust_category':   return \`<td>\${bustBadge(p)}</td>\`;
        default:                return \`<td>\${p[c.k]||'—'}</td>\`;
      }
    }).join('');
    return \`<tr class="\${rc}" style="cursor:pointer" onclick="toggleScorecard('\${p.player.replace(/'/g,"\\\\'")}',this)">\${cells}</tr>\`;
  }).join('');
  // Pagination bar
  document.getElementById('boardCount').innerHTML=renderPagination(allData.length, tp);
  console.log('[Board] loaded='+board.length+' showing='+data.length+'/'+allData.length+' page='+_bPage+'/'+tp);
}
function renderPagination(total, tp){
  const showing1=Math.min((_bPage-1)*PAGE_SIZE+1,total);
  const showing2=Math.min(_bPage*PAGE_SIZE,total);
  if(tp<=1) return \`<span style="font-size:11px;color:var(--muted)">Loaded: \${board.length} players | Showing: \${total}</span>\`;
  const pages=[];
  for(let i=1;i<=tp;i++){
    if(i===1||i===tp||Math.abs(i-_bPage)<=2) pages.push(i);
    else if(pages[pages.length-1]!=='…') pages.push('…');
  }
  return \`<div style="display:flex;align-items:center;gap:6px;flex-wrap:wrap;margin-top:6px">
    <span style="font-size:11px;color:var(--muted)">Loaded: \${board.length} | Showing \${showing1}-\${showing2} of \${total}</span>
    <button class="pill" onclick="goPage(\${_bPage-1})" \${_bPage<=1?'disabled':''} style="padding:3px 9px">← Prev</button>
    \${pages.map(p=>p==='…'?\`<span style="color:var(--muted)">…</span>\`:
      \`<button class="pill \${p===_bPage?'on':''}" onclick="goPage(\${p})" style="padding:3px 9px">\${p}</button>\`).join('')}
    <button class="pill" onclick="goPage(\${_bPage+1})" \${_bPage>=tp?'disabled':''} style="padding:3px 9px">Next →</button>
  </div>\`;
}
function goPage(p){ const all=getFilteredBoard(); const tp=totalPages(all); _bPage=Math.max(1,Math.min(p,tp)); renderBoard(); document.getElementById('boardTbl').scrollIntoView({behavior:'smooth',block:'start'}); }`;

html = html.slice(0, renderBoardStart) + NEW_RENDER_BOARD + html.slice(renderBoardEndFull);
console.log('✅ Replaced renderBoard with paginated + column-aware version');

// ─────────────────────────────────────────────────────────────────────────────
// 10. Fix table header to use dynamic renderBoardHeader + add ⚙️ button
// ─────────────────────────────────────────────────────────────────────────────
// Replace static thead with a dynamic one + add column toggle button
html = html.replace(
  `    <input class="sbox" id="boardQ" placeholder="Search player…" oninput="renderBoard()">`,
  `    <input class="sbox" id="boardQ" placeholder="Search player…" oninput="_bPage=1;renderBoard()">
    <button class="pill" onclick="document.getElementById('colToggle').classList.toggle('open')" title="Toggle columns" style="padding:5px 11px;position:relative">⚙️ Cols
      <div id="colToggle" class="col-toggle-panel">
        <div style="font-size:11px;font-weight:700;margin-bottom:8px;color:var(--text)">Visible Columns</div>
        <div id="colTogglePanel"></div>
        <button class="btn btn-go" style="margin-top:8px;padding:5px 12px;font-size:11px" onclick="resetCols()">Reset Default</button>
      </div>
    </button>`
);

// Replace static thead with dynamic placeholder
html = html.replace(
  `      <thead><tr>
        <th onclick="setBSort('my_rank')">Rank<span id="bs-my_rank"></span></th>
        <th onclick="setBSort('master_score')">⭐<span id="bs-master_score"> ▼</span></th>
        <th onclick="setBSort('player')">Player<span id="bs-player"></span></th>
        <th>Pos</th><th>Team</th>
        <th onclick="setBSort('age')">Age<span id="bs-age"></span></th>
        <th onclick="setBSort('proj_pts_2026')">Proj<span id="bs-proj_pts_2026"></span></th>
        <th onclick="setBSort('vorp_adjusted')">VORP<span id="bs-vorp_adjusted"></span></th>
        <th onclick="setBSort('ceiling_score')">Ceil<span id="bs-ceiling_score"></span></th>
        <th onclick="setBSort('floor_score_v2')">Floor<span id="bs-floor_score_v2"></span></th>
        <th onclick="setBSort('injury_risk_score')">🩹<span id="bs-injury_risk_score"></span></th>
        <th onclick="setBSort('target_round')">Tgt<span id="bs-target_round"></span></th>
        <th onclick="setBSort('dp_value_2qb')">DP Val<span id="bs-dp_value_2qb"></span></th>
        <th>Flag</th>
      </tr></thead>`,
  `      <thead id="boardThead"></thead>`
);

// ─────────────────────────────────────────────────────────────────────────────
// 11. Add CSS for column toggle panel
// ─────────────────────────────────────────────────────────────────────────────
html = html.replace(
  `/* ── Taxi grade badges ── */`,
  `/* ── Column toggle panel ── */
.col-toggle-panel{display:none;position:absolute;top:110%;right:0;z-index:200;background:#0d1827;border:1px solid var(--border);border-radius:7px;padding:12px 14px;min-width:180px;box-shadow:0 8px 24px rgba(0,0,0,.6)}
.col-toggle-panel.open{display:block}

/* ── Taxi grade badges ── */`
);

// ─────────────────────────────────────────────────────────────────────────────
// 12. Add resetCols function and wire up init to call renderColToggle
// ─────────────────────────────────────────────────────────────────────────────
html = html.replace(
  `  renderStatCards();
  renderBoard();
  initDraftState();
}`,
  `  renderStatCards();
  renderColToggle();
  renderBoard();
  initDraftState();
}
function resetCols(){ _visibleCols=[...DEFAULT_COLS]; saveColPrefs(); renderColToggle(); renderBoardHeader(); renderBoard(); }`
);

// ─────────────────────────────────────────────────────────────────────────────
// 13. Add loading spinner to table body (shows before JS runs)
// ─────────────────────────────────────────────────────────────────────────────
html = html.replace(
  `      <tbody id="boardBody"></tbody>`,
  `      <tbody id="boardBody"><tr><td colspan="14" style="text-align:center;padding:40px;color:var(--muted)"><span id="loadSpinner">⏳ Loading draft board</span></td></tr></tbody>`
);

// ─────────────────────────────────────────────────────────────────────────────
// 14. Fix scorecard to not use p.bust_flag
// ─────────────────────────────────────────────────────────────────────────────
// Already fixed in previous session — just verify bust_flag doesn't appear
if (html.includes('p.bust_flag')) {
  html = html.replace(/p\.bust_flag==1/g, "p.bust_category==='GEM'");
  console.log('⚠️ Fixed remaining bust_flag references');
}

// ─────────────────────────────────────────────────────────────────────────────
// Write output
// ─────────────────────────────────────────────────────────────────────────────
fs.writeFileSync('/home/user/Fantasy-Tracker/index.html', html);
const finalSize = fs.statSync('/home/user/Fantasy-Tracker/index.html').size;
console.log(`\n✅ index.html written — ${Math.round(finalSize/1024)}KB (was 150KB)`);
console.log('Run syntax check next.');
